In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4,6,-5,3])

In [4]:
obj

0    4
1    6
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  6, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -4, 3], idnex=['d', 'b', 'a', 'c'])

TypeError: __init__() got an unexpected keyword argument 'idnex'

In [10]:
obj2 = pd.Series([4, 7, -4, 3], index=['d', 'b', 'a', 'c'])

In [11]:
obj2

d    4
b    7
a   -4
c    3
dtype: int64

In [12]:
obj2['a']

-4

In [13]:
obj2['b']

7

In [14]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d     8
b    14
a    -8
c     6
dtype: int64

In [16]:
np.exp(obj2)

NameError: name 'np' is not defined

In [17]:
import numpy as np

In [18]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.018316
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'ohio':333, 'ss': 234}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

ohio    333
ss      234
dtype: int64

In [27]:
states = ['ss','ohio','as']

In [28]:
obj4 = pd.Series(sdata, index=states)

In [29]:
obj4


ss      234.0
ohio    333.0
as        NaN
dtype: float64

In [30]:
pd.isnull(obj4)

ss      False
ohio    False
as       True
dtype: bool

In [31]:
pd.notnull(obj4)

ss       True
ohio     True
as      False
dtype: bool

In [32]:
obj4.isnull()

ss      False
ohio    False
as       True
dtype: bool

In [33]:
obj3

ohio    333
ss      234
dtype: int64

In [34]:
obj4


ss      234.0
ohio    333.0
as        NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4

ss      234.0
ohio    333.0
as        NaN
Name: population, dtype: float64

In [37]:
obj4.index.name = 'state'

In [38]:
obj4

state
ss      234.0
ohio    333.0
as        NaN
Name: population, dtype: float64

In [39]:
obj

0    4
1    6
2   -5
3    3
dtype: int64

In [40]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [41]:
obj

Bob      4
Steve    6
Jeff    -5
Ryan     3
dtype: int64

In [42]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year':[2000, 2001, 2002, 2001, 2002, 20003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]
}

In [43]:
frame = pd.DataFrame(data)

In [44]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   2001  1.7
2    Ohio   2002  3.6
3  Nevada   2001  2.4
4  Nevada   2002  2.9
5  Nevada  20003  3.2

In [45]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [46]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0   2000    Ohio  1.5
1   2001    Ohio  1.7
2   2002    Ohio  3.6
3   2001  Nevada  2.4
4   2002  Nevada  2.9
5  20003  Nevada  3.2

In [47]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])

In [48]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     2001    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four    2001  Nevada  2.4  NaN
five    2002  Nevada  2.9  NaN
six    20003  Nevada  3.2  NaN

In [49]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [50]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [51]:
frame2.year

one       2000
two       2001
three     2002
four      2001
five      2002
six      20003
Name: year, dtype: int64

In [52]:
frame2['year']

one       2000
two       2001
three     2002
four      2001
five      2002
six      20003
Name: year, dtype: int64

In [53]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5

In [55]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5  16.5
two     2001    Ohio  1.7  16.5
three   2002    Ohio  3.6  16.5
four    2001  Nevada  2.4  16.5
five    2002  Nevada  2.9  16.5
six    20003  Nevada  3.2  16.5

In [56]:
frame2['debt'] = np.arange(6)

In [57]:
frame2


year   state  pop  debt
one     2000    Ohio  1.5     0
two     2001    Ohio  1.7     1
three   2002    Ohio  3.6     2
four    2001  Nevada  2.4     3
five    2002  Nevada  2.9     4
six    20003  Nevada  3.2     5

In [58]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [59]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [60]:
frame2['debt'] = val

In [61]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six    20003  Nevada  3.2   NaN

In [62]:
frame2['eastern'] = frame2.state == 'Ohio'

In [63]:
frame2

year   state  pop  debt  eastern
one     2000    Ohio  1.5   NaN     True
two     2001    Ohio  1.7  -1.2     True
three   2002    Ohio  3.6   NaN     True
four    2001  Nevada  2.4  -1.5    False
five    2002  Nevada  2.9  -1.7    False
six    20003  Nevada  3.2   NaN    False

In [64]:
del frame2['eastern']

In [65]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six    20003  Nevada  3.2   NaN

In [66]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [67]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [68]:
frame3 = pd.DataFrame(pop)

In [69]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six    20003  Nevada  3.2   NaN

In [70]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six    20003  Nevada  3.2   NaN

In [71]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [72]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [73]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

AttributeError: 'list' object has no attribute 'astype'

In [75]:
pd.DataFrame(frame3, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [76]:
pdata = {'Ohio': frame3['Ohio'][: -1],
         'Nevada': frame3['Nevada'][:2]
        }

In [77]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [78]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [79]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [80]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [81]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [82]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [83]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [20003, 'Nevada', 3.2, nan]], dtype=object)

In [84]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [85]:
obj 

a    0
b    1
c    2
dtype: int64

In [86]:
index = obj.index

In [87]:
index

Index(['a', 'b', 'c'], dtype='object')

In [88]:
index[1:]

Index(['b', 'c'], dtype='object')

In [89]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [90]:
labels = pd.Index(np.arange(3))

In [91]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [92]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [93]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [94]:
labels1 = pd.index(np.arange(3))

AttributeError: module 'pandas' has no attribute 'index'

In [95]:
obj2.index is labels

True

In [96]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [97]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [98]:
'Ohio' in frame3.columns

True

In [99]:
2003 in frame3.index

False

In [100]:
dup_labels = pd.Index(['F','F','T','T'])

In [101]:
dup_labels

Index(['F', 'F', 'T', 'T'], dtype='object')

In [102]:
pd.unique(dup_labels)

array(['F', 'T'], dtype=object)

In [103]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [104]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [105]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [106]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [107]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [108]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [109]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [110]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [111]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [112]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [113]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [114]:
states = ['Texas', 'Utah', 'California']

In [115]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [116]:
frame.loc[['a', 'b', 'c', 'd'], states]

c:\users\h\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [117]:
onj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])

In [118]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [119]:
onj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [120]:
obj = onj

In [121]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [122]:
new_obj = obj.drop('c')

In [123]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [124]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int32

In [125]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [126]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [129]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [130]:
obj.drop('c', inplace=True)

In [131]:
obj

a    0
b    1
d    3
e    4
dtype: int32

In [132]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [133]:
obj = pd.Series(np.arange(4), index=['a', 'b', 'c', 'd'])

In [134]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [135]:
obj['b']

1

In [137]:
obj[1]

1

In [138]:
obj[2:4]

c    2
d    3
dtype: int32

In [139]:
obj[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: int32

In [140]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [141]:
obj[obj<2]

a    0
b    1
dtype: int32

In [142]:
obj['b':'c']

b    1
c    2
dtype: int32

In [143]:
obj['b':]

b    1
c    2
d    3
dtype: int32

In [144]:
obj['b':'c'] = 5

In [145]:
obj

a    0
b    5
c    5
d    3
dtype: int32

In [146]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [147]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [148]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [149]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [150]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [151]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [152]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [153]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [154]:
data[data < 5] = 0

In [155]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [156]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [157]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [158]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [159]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [160]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [161]:
data.iloc[[1,2]]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11

In [162]:
ser = pd.Series(np.arange(3))

In [163]:
ser

0    0
1    1
2    2
dtype: int32

In [167]:
ser.iloc[1]

1

In [168]:
ser.iloc[-1]

2

In [169]:
ser[:1]

0    0
dtype: int32

In [170]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [171]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [172]:
data['Ohio':'Utah']

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11

In [173]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [174]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [176]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [177]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [178]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [179]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [180]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [181]:
df2 = pd.DataFrame(np.arange(12).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [182]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [183]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [184]:
df1 = pd.DataFrame({'A': [1, 2]})

In [185]:
df2 = pd.DataFrame({'B': [3, 4]})

In [186]:
df1

A
0  1
1  2

In [187]:
df2

B
0  3
1  4

In [188]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [189]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [190]:
df1 = pd.DataFrame(np.arange(12).reshape((3, 4)), columns=list('abcd'))

In [191]:
df2 = pd.DataFrame(np.arange(20).reshape((4 ,5)), columns=list('abcde'))

In [192]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [193]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [194]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [195]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [196]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [197]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [198]:
arr = np.arange(12).reshape((3, 4))

In [199]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [200]:
arr[0]

array([0, 1, 2, 3])

In [201]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [202]:
df1 = pd.DataFrame(np.arange(12).reshape((3, 4)), columns=list('abcd'))

In [203]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [204]:
series = df1.iloc[0]

In [205]:
series

a    0
b    1
c    2
d    3
Name: 0, dtype: int32

In [206]:
df1 - series

a  b  c  d
0  0  0  0  0
1  4  4  4  4
2  8  8  8  8

In [207]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [208]:
frame.apply(f)

Ohio  Texas  California
min     0      1           2
max     6      7           8

In [209]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [210]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [211]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [212]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'])

In [213]:
frame

0  1  2  3
three  0  1  2  3
one    4  5  6  7

In [214]:
frame.sort_index()

0  1  2  3
one    4  5  6  7
three  0  1  2  3

In [215]:
frame.sort_index(axis=1)

0  1  2  3
three  0  1  2  3
one    4  5  6  7

In [216]:
frame[0]

three    0
one      4
Name: 0, dtype: int32

In [217]:
frame['three']

KeyError: 'three'

In [218]:
frame.loc['three']

0    0
1    1
2    2
3    3
Name: three, dtype: int32

In [219]:
frame.sort_index(axis=1, ascending=False)

3  2  1  0
three  3  2  1  0
one    7  6  5  4

In [220]:
obj = pd.Series([4,7,-3,2])

In [221]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [222]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [223]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [224]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [225]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [226]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})

In [227]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [228]:
frame.sort_values()

TypeError: sort_values() missing 1 required positional argument: 'by'

In [229]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [230]:
frame.sort_values(by=['a',  'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [231]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [232]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [233]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [234]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [235]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [236]:
obj.index.is_unique

False

In [237]:
obj['a']

a    0
a    1
dtype: int64

In [239]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [240]:
df

0         1         2
a -0.047729  1.208120  0.641847
a -0.358597  0.924337 -0.129657
b  1.015744  0.603226 -0.803664
b  0.055932  1.138499  0.024052

In [241]:
df.loc['b']

0         1         2
b  1.015744  0.603226 -0.803664
b  0.055932  1.138499  0.024052

In [242]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]], index=list('abcd'), columns=['one', 'two'])

In [243]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [244]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [245]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [246]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [247]:
df.idxmax()

one    b
two    d
dtype: object

In [248]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [249]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [250]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [251]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [252]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object