### 1. 导入numpy库并简写为 np

In [1]:
import numpy as np

### 2. 打印numpy的版本和配置说明 

In [2]:
print(np.__version__)

1.15.4


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_op

### 3. 创建一个长度为10的空向量

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. 如何找到任何一个数组的内存大小？

In [7]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


### 5. 如何从命令行得到numpy中add函数的说明文档? 

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6. 创建一个长度为10并且除了第五个值为1的空向量

In [10]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. 创建一个值域范围从10到49的向量

In [11]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. 反转一个向量(第一个元素变为最后一个) 

In [12]:
Z = np.arange(40)
Z = Z[::-1]
print(Z)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### 9. 创建一个 3x3 并且值从0到8的矩阵

In [17]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 

In [20]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


### 11. 创建一个 3x3 的单位矩阵

In [21]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. 创建一个 3x3x3的随机数组 

In [24]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.14109986 0.00738082 0.32133279]
  [0.67813545 0.07314917 0.91611782]
  [0.15087362 0.77427588 0.24336283]]

 [[0.56354366 0.97167524 0.71921539]
  [0.9257828  0.63372445 0.06631547]
  [0.78485958 0.53260848 0.08518427]]

 [[0.01220284 0.29675421 0.91834504]
  [0.52227293 0.32017636 0.23891222]
  [0.88184838 0.67141301 0.41406289]]]


### 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [2]:
import numpy as np
Z = np.random.random((10,10))
print(Z.min(),Z.max())

0.037660542217129556 0.9486980197289798


### 14. 创建一个长度为30的随机向量并找到它的平均值 

In [3]:
Z = np.random.random(30)
print(Z.mean())

0.515877752481116


### 15. 创建一个二维数组，其中边界值为1，其余值为0

In [4]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. 对于一个存在在数组，如何添加一个用0填充的边界? 

In [5]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. 以下表达式运行的结果分别是什么?

In [6]:
print(0 * np.nan)

nan


In [7]:
print(np.nan == np.nan)

False


In [8]:
print(np.inf > np.nan)

False


In [9]:
print(np.nan - np.nan)

nan


In [10]:
print(0.3 == 3 * 0.1)

False


### 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [11]:
Z = np.diag(1 + np.arange(4),k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [12]:
Z = np.zeros((8,8),dtype = int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [13]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


### 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [14]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. 对一个5x5的随机矩阵做归一化

In [15]:
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(),Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.86448903 0.08857768 0.75257124 0.09452103 0.03983374]
 [0.42891845 0.         0.71539056 0.58730243 1.        ]
 [0.96045562 0.79342444 0.41678423 0.31981129 0.1666648 ]
 [0.03495104 0.76835872 0.33038772 0.75671389 0.19635058]
 [0.92051545 0.50713557 0.8694613  0.97516789 0.25707458]]


### 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [22]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [26]:
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [37]:
Z = np.arange(12)
print(Z)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11]


### 26. 下面脚本运行后的结果是什么? 

In [44]:
print(sum(range(5),-1))

10


### 27. 考虑一个整数向量Z,下列表达合法的是哪个?

In [54]:
Z = np.arange(5)
print(Z ** Z)
print(2 << Z >> 2)
print(Z<- Z)
print(1j*Z) 
print(Z/1/1)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


### 28. 下列表达式的结果分别是什么?

In [60]:
#print(np.array(0) / np.array(0))
#print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


### 29. 如何从零位对浮点数组做舍入 ? 

In [61]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 3.  7. -6.  9. -5.  3.  3.  4. -8. -9.]


### 30. 如何找到两个数组中的共同元素? 

In [2]:
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 5 6 7 9]


### 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [10]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

### 32. 下面的表达式是正确的吗?

In [11]:
np.sqrt(-1) == np.emath.sqrt(-1)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

### 33. 如何得到昨天，今天，明天的日期?

In [13]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


### 34. 如何得到所有与2016年7月对应的日期

In [14]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [16]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36. 用五种不同的方法去提取一个随机数组的整数部分

In [17]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[7. 3. 5. 5. 6. 3. 6. 5. 4. 2.]
[7. 3. 5. 5. 6. 3. 6. 5. 4. 2.]
[7. 3. 5. 5. 6. 3. 6. 5. 4. 2.]
[7 3 5 5 6 3 6 5 4 2]
[7. 3. 5. 5. 6. 3. 6. 5. 4. 2.]


### 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [18]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [19]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [20]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. 创建一个长度为10的随机向量，并将其排序

In [21]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.07445607 0.08527182 0.4075002  0.41975671 0.5165019  0.55019653
 0.55642185 0.72758761 0.87786644 0.93235524]


### 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [22]:
Z = np.arange(10)
np.add.reduce(Z)

45

### 42. 对于两个随机数组A和B，检查它们是否相等

In [23]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


### 43. 创建一个只读数组(read-only)

In [24]:
Z = np.zeros(10)
Z.flags.writeable = False

### 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [25]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.03263033 1.02161566 0.41507908 0.87947501 0.50888042 0.90629135
 1.12960959 1.26755035 0.67348316 0.70305472]
[0.65803171 1.27509638 1.18920277 0.08498997 1.29536352 0.15050892
 0.58158717 0.77756314 0.50266301 1.10154826]


### 45. 创建一个长度为10的向量，并将向量中最大值替换为1 

In [26]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.55146376 0.33971749 0.61008275 0.62780143 0.         0.29596314
 0.6453823  0.23510528 0.30572008 0.42368495]


### 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 

In [27]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [28]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


### 48. 打印每个numpy标量类型的最小值和最大值

In [30]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49. 如何打印一个数组中的所有数值?

In [31]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 50. 给定标量时，如何找到数组中最接近标量的值？

In [33]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

21


### 51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

In [34]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


### 52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离

In [35]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.47122706 0.39061937 0.4577945  0.16566007 0.67326047
  0.48201519 0.25974073 0.47419717 0.71020391]
 [0.47122706 0.         0.39195166 0.14211983 0.63421357 0.32972035
  0.0132672  0.47788209 0.55625212 0.93889793]
 [0.39061937 0.39195166 0.         0.26701536 0.52679227 0.71638252
  0.40467182 0.18022146 0.16467402 0.54999992]
 [0.4577945  0.14211983 0.26701536 0.         0.62288507 0.4705891
  0.15254708 0.38866879 0.42741334 0.816822  ]
 [0.16566007 0.63421357 0.52679227 0.62288507 0.         0.80916593
  0.64455381 0.36500546 0.57498967 0.72525745]
 [0.67326047 0.32972035 0.71638252 0.4705891  0.80916593 0.
  0.31838685 0.77145864 0.88099308 1.25468219]
 [0.48201519 0.0132672  0.40467182 0.15254708 0.64455381 0.31838685
  0.         0.49111283 0.56887462 0.9519108 ]
 [0.25974073 0.47788209 0.18022146 0.38866879 0.36500546 0.77145864
  0.49111283 0.         0.21549686 0.49566929]
 [0.47419717 0.55625212 0.16467402 0.42741334 0.57498967 0.88099308
  0.56887462 0.215496

### 53. 如何将32位的浮点数(float)转换为对应的整数(integer)

In [36]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 54. 如何读取以下文件

In [38]:
from io import StringIO
 
# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


### 55. 对于numpy数组，enumerate的等价操作是什么

In [39]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56. 生成一个通用的二维Gaussian-like数组 

In [40]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### 57. 对一个二维数组，如何在其内部随机放置p个元素?

In [1]:
import numpy as np
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
